version: '3.8'

services:
  bot:
    build: .
    container_name: copperx-telegram-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOG_DIR=/app/logs