version: '3.8'

services:
  bot:
    build: .
    container_name: copperx-telegram-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOG_DIR=/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"